### ISSUE TITLE
Reverse engineering the app

### ISSUE THREAD

**Issue by kauegimenes** [ArminKaric/Project-Royale#3]
Hello, you got any lucky reverse engineering the app?
I am trying to get Clan and Player information from the app, i tried using Fiddler for both Android and iPhone apps but no luck so far, looks like the app knows i am using a proxy or a fake certificate to decrypt HTTPS requests.

**Comment by ArminKaric** [comment]
Nope, Supercell really has prevented any sorts of reverse engineering (Sadly).
